const projects = [
  {
    id: 1,
    title: "Ek Kamra",
    role: "Director and Cinematographer",
    year: "2025",
    description:
      "Directed and shot the video with a minimalist aesthetic and a strong emotional narrative",
    image: "/thumbnails/ek-kamra.png",
    category: "Music Video",
    details: {
      date: "March 2025",
      location: "Gurgaon, India",
      company: "Independent",
      artist: "AK$HAR",
      director: "Raghav Raj Sobti & Dhiren",
      type: "Music Video",
      videos: [
        {
          url: "https://www.youtube.com/embed/28Mb1cIooGw",
          platform: "youtube",
        },
      ],
    },
  },
  // {
  //   id: 2,
  //   title: "BoxoutFM & Premise",
  //   role: "Videographer",
  //   year: "2024-2025",
  //   description:
  //     "Covered live DJ sets and captured underground electronic music culture",
  //   image: "/images/boxout.jpg",
  //   category: "event",
  //   details: {
  //     date: "January 2025",
  //     location: "Delhi, India",
  //     company: "BoxoutFM",
  //     artist: "Various Artists",
  //     director: "Your Name",
  //     type: "Event Coverage",
  //     videos: [
  //       { url: "https://www.youtube.com/embed/example3", platform: "youtube" },
  //     ],
  //   },
  // },
  {
    id: 3,
    title: "Dead Dreams",
    role: "Director and Cinematographer",
    year: "2024",
    description:
      "From the depths of darkness, even the faintest spark can ignite a new beginning.",
    image: "/thumbnails/dead-dreams.png",
    category: "short-film",
    details: {
      date: "November 2024",
      location: "Gurgaon, India",
      company: "Independent",
      artist: "Harsh Pratap Singh",
      director: "Raghav / Ketan / Dhiren",
      type: "Short Film",
      videos: [
        {
          url: "https://www.youtube.com/embed/79ooo0YE5fY",
          platform: "youtube",
        },
      ],
    },
  },
  {
    id: 4,
    title: "Beneath the surface",
    role: "Cinematographer",
    year: "2024",
    description:
      "We all wear masks, hiding the emotions we don’t know how to express.",
    image: "/thumbnails/BTS.png",
    category: "short-film",
    details: {
      date: "November 2024",
      location: "Gurgaon, India",
      company: "Independent",
      artist: "Abid",
      director: "Raghav / Ketan / Dhiren",
      type: "Short Film",
      videos: [
        {
          url: "https://www.youtube.com/embed/Uzu819p0hL8",
          platform: "youtube",
        },
      ],
    },
  },
  {
    id: 5,
    title: "Narazi",
    role: "Cinematographer",
    year: "2024",
    description:
      "Black and white film on 'Kun Faya Kun' with a fresh visual take on loneliness.",
    image: "/thumbnails/narazi.png",
    category: "short-film",
    details: {
      date: "November 2024",
      location: "Gurgaon, India",
      company: "Independent",
      artist: "Harsh Pratap Singh",
      director: "Raghav / Ketan / Dhiren",
      type: "Short Film",
      videos: [
        {
          url: "https://www.youtube.com/embed/CVIGswYIsUM",
          platform: "youtube",
        },
      ],
    },
  },
  {
    id: 6,
    title: "Socially trapped // Socially free",
    role: "Director / Cinematographer",
    year: "2024",
    description: "Breaking free from the fake online life to embrace reality.",
    image: "/thumbnails/stsf.png",
    category: "short-film",
    details: {
      date: "November 2024",
      location: "Gurgaon, India",
      company: "Independent",
      artist: "Abid",
      director: "Raghav / Ketan / Dhiren",
      type: "Short Film",
      videos: [
        {
          url: "https://www.youtube.com/embed/xjacCCS0Y9Q",
          platform: "youtube",
        },
      ],
    },
  },
  {
    id: 7,
    title: "TIMEOUT",
    role: "Director / Cinematographer",
    year: "2024",
    description: "The difference between succeeding and failing is TRYING!",
    image: "/thumbnails/timeout.png",
    category: "short-film",
    details: {
      date: "November 2024",
      location: "Gurgaon, India",
      company: "Independent",
      artist: "Ishaan",
      director: "Raghav",
      type: "Short Film",
      videos: [
        {
          url: "https://www.youtube.com/embed/BxU_oYhwwNs",
          platform: "youtube",
        },
      ],
    },
  },
  {
    id: 8,
    title: "Jahnvi @ Hard Rock cafe",
    role: "Videographer",
    year: "2025",
    description: "A raw Documentary Form set recording for Jahnvi",
    image: "/thumbnails/jahnvi.png",
    category: "event",
    details: {
      date: "May 2025",
      location: "Delhi, India",
      company: "Independent",
      artist: "Jahnvi",
      director: "Raghav",
      type: "Event Coverage",
      videos: [
        {
          url: "https://www.youtube.com/embed/UC8VuiWBDPw",
          platform: "youtube",
        },
      ],
    },
  },
  {
    id: 9,
    title: "Jahnvi Interview",
    role: "Videographer",
    year: "2025",
    description:
      "90 sec interview where Jahnvi is raw and vulnerable before her festival set.",
    image: "/thumbnails/jahnvi2.png",
    category: "interview",
    details: {
      date: "April 2025",
      location: "Delhi, India",
      company: "Premise",
      artist: "Jahnvi",
      director: "Raghav",
      type: "Interview",
      videos: [{ url: "DJPJWiMTcIl", platform: "instagram" }], // Changed to just post ID
    },
  },
  {
    id: 10,
    title: "Laksh Interview",
    role: "Videographer",
    year: "2025",
    description:
      "A storyteller who revives folklore and culture through lyrical depth.",
    image: "/thumbnails/laksh.jpg",
    category: "interview",
    details: {
      date: "March 2025",
      location: "Delhi, India",
      company: "Premise",
      artist: "Laksh",
      director: "Raghav",
      type: "Interview",
      videos: [{ url: "DHdxbxSTuAu", platform: "instagram" }], // Changed to just post ID
    },
  },
  {
    id: 11,
    title: "Delhi Gate Showreel",
    role: "Videographer",
    year: "2025",
    description: "Showreel of Delhi Gate's underground rap event @ Piano Man.",
    image: "/thumbnails/delhigate.jpg",
    category: "showreel",
    details: {
      date: "January 2025",
      location: "Delhi, India",
      company: "Premise",
      artist: "Various",
      director: "Raghav",
      type: "Showreel",
      videos: [{ url: "DHdF3gyorF-", platform: "instagram" }], // Changed to just post ID
    },
  },
   {
    id: 12,
    title: "Bandhan Indian Wear Showreel",
    role: "Videographer",
    year: "2025",
    description: "Showreel of Bandhan's New line of Indian Wear @ Humayun Tomb",
    image: "/thumbnails/porash.jpg",
    category: "showreel",
    details: {
      date: "February 2025",
      location: "Humayun Tomb, India",
      company: "Bandhan",
      artist: "Porash Mishra",
      director: "Raghav",
      type: "Showreel",
      videos: [{ url: "DGsNRvwtlX4", platform: "instagram" }], 
    },
  },
     {
    id: 13,
    title: "Bandhan Western Wear Showreel",
    role: "Videographer",
    year: "2025",
    description: "Showreel of Bandhan's New line of Western Wear ",
    image: "/thumbnails/porash2.jpg",
    category: "showreel",
    details: {
      date: "February 2025",
      location: "Delhi, India",
      company: "Bandhan",
      artist: "Porash Mishra",
      director: "Raghav",
      type: "Showreel",
      videos: [{ url: "DIzAjRGIOOU", platform: "instagram" }], 
    },
  },
    {
    id: 14,
    title: "NPS for Flexibility",
    role: "Intern AD",
    year: "2023",
    description: "Ad film for the mobile app National Pension scheme",
    image: "/thumbnails/nps1.png",
    category: "Ad Film",
    details: {
      date: "October 2023",
      location: "Mumbai, India",
      company: "Classic Films",
      artist: "Arpit Choudhary",
      director: "Abhay Nihalani",
      type: "ad film",
      videos: [{ url: "https://www.youtube.com/embed/oLjqyQlZ75U",
          platform: "youtube" }], 
    },
  },

   {
    id: 15,
    title: "NPS for Transparency",
    role: "Intern AD",
    year: "2023",
    description: "Ad film for the mobile app National Pension scheme",
    image: "/thumbnails/nps2.png",
    category: "Ad Film",
    details: {
      date: "October 2023",
      location: "Mumbai, India",
      company: "Classic Films",
      artist: "Arpit Choudhary",
      director: "Abhay Nihalani",
      type: "ad film",
      videos: [{ url: "https://www.youtube.com/embed/BZL_kGt-zRQ",
          platform: "youtube" }], 
    },
  },
   {
    id: 16,
    title: "NPS for Portability",
    role: "Intern AD",
    year: "2023",
    description: "Ad film for the mobile app National Pension scheme",
    image: "/thumbnails/nps3.png",
    category: "Ad Film",
    details: {
      date: "October 2023",
      location: "Mumbai, India",
      company: "Classic Films",
      artist: "Arpit Choudhary",
      director: "Abhay Nihalani",
      type: "ad film",
      videos: [{ url: "https://www.youtube.com/embed/7WAAMXyT4l8",
          platform: "youtube" }], 
    },
  },
   {
    id: 17,
    title: "NPS for Trust",
    role: "Intern AD",
    year: "2023",
    description: "Ad film for the mobile app National Pension scheme",
    image: "/thumbnails/nps4.png",
    category: "Ad Film",
    details: {
      date: "October 2023",
      location: "Mumbai, India",
      company: "Classic Films",
      artist: "Arpit Choudhary",
      director: "Abhay Nihalani",
      type: "ad film",
      videos: [{ url: "https://www.youtube.com/embed/qguwlDHest0",
          platform: "youtube" }], 
    },
  },
   {
    id: 18,
    title: "Khwaab",
    role: "Assistant Director",
    year: "2024",
    description: "Khwaab means unrequited love. A kind of love where feelings are not reciprocated. The song expresses the feelings one goes through and it reminds of the days gone by",
    image: "/thumbnails/khwaab.png",
    category: "Music Video",
    details: {
      date: "September 2024",
      location: "Kashmir, India",
      company: "Artiste First",
      artist: "Faheem Abdullah and PHO",
      director: "Imbesat Ahmad & Oun Mehdi",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/EWIay_vyFMk",
          platform: "youtube" }], 
    },
  },
   {
    id: 19,
    title: "Rooh Music Film",
    role: "2nd Assistant Director",
    year: "2024",
    description: "A song that describes deep love. In this state of passionate love, you see your lover as perfect, almost unreal, like a divine being.",
    image: "/thumbnails/rooh.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Ladakh, India",
      company: "Artiste First",
      artist: "Rekha Bhardwaj, Arslan Nizami",
      director: "Jomin Varghese ",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/EWIay_vyFMk",
          platform: "youtube" }], 
    },
  },
   {
    id: 20,
    title: "Masa Rosh",
    role: "2nd Assistant Director",
    year: "2024",
    description: "Masa Rosh is a playful song that captures the essence of making amends in a fun and endearing way. It's a song about playful apologies, cheeky charm, and the joy of making up to someone.",
    image: "/thumbnails/masa.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami  ,Siddharth Pandit",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/Gt7_LUqnldo",
          platform: "youtube" }], 
    },
  },
   {
    id: 21,
    title: "Mora Piya",
    role: "2nd Assistant Director",
    year: "2024",
    description: "The song talks about a heart yearning for its beloved. The lyrics express a deep sense of longing, as they eagerly awaits the arrival of their love, their heart pounding with each passing moment.",
    image: "/thumbnails/mora.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Shradha Mishra",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/y0g1uj3OE_Y",
          platform: "youtube" }], 
    },
  },
   {
    id: 22,
    title: "Fanna Fillah ",
    role: "2nd Assistant Director",
    year: "2024",
    description: " The song gives hope, reminding us that even when we feel lost, we will eventually find our way. It’s a song that resonates with today’s generation, who often feel lost in their own thoughts, overwhelmed by the complexities of life.",
    image: "/thumbnails/fanna.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Faheem Abdullah , Siddharth Pandit",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/mm48gpsJ9bQ",
          platform: "youtube" }], 
    },
  },
   {
    id: 23,
    title: "Dhamaal",
    role: "2nd Assistant Director",
    year: "2025",
    description: "Dhamaal is a song that captures the intense emotional journey of someone searching for their love and the joy that would have come if they have got that love.",
    image: "/thumbnails/dhamaal.png",
    category: "Music Video",
    details: {
      date: "February 2025",
      location: "Kashmir, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Faheem Abdullah , Qaisar Nizami , Aman Moroney",
      director: "Faheem Abdullah",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/EKET-n4cBHI",
          platform: "youtube" }], 
    },
  },
   {
    id: 24,
    title: "Tu kahan hai",
    role: "2nd Assistant Director",
    year: "2024",
    description: "Tu Kahan Hai is a journey of self-discovery, a quest for meaning. 'Tu Kahan Hai' is an exploration of identity, purpose, and the human condition.",
    image: "/thumbnails/kahan.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/GQn3vTTKo9g",
          platform: "youtube" }], 
    },
  },
   {
    id: 25,
    title: "Zamane Ki Zanjeer",
    role: "2nd Assistant Director",
    year: "2024",
    description: "Zamane Ki Zanjeer delves into the themes of existentialism, and social demons. It explores the human condition, questioning the purpose of life and the nature of reality. ",
    image: "/thumbnails/zanjeer.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Farozan Nizami , Huzaif Nazar ",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/xk1qELGYnDQ",
          platform: "youtube" }], 
    },
  },
   {
    id: 26,
    title: "Dard-e-Maa ",
    role: "2nd Assistant Director",
    year: "2024",
    description: "Dard-e-Maa is a mystical song blending Hafiz's and Shamas Faqir’s Persian poetry with Kashmiri influences. It symbolizes a door that leads listeners to a personal, journey.",
    image: "/thumbnails/dardemaa.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/dBUTXHooqF0",
          platform: "youtube" }], 
    },
  },
   {
    id: 27,
    title: "Saba Ke Baad",
    role: "2nd Assistant Director",
    year: "2024",
    description: "A song that describes deep, love. In this state of passionate love, you see your lover as perfect, almost unreal, like a divine being.",
    image: "/thumbnails/sabba.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Zeeshaan Nabi",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/nFQTEXzwFqI",
          platform: "youtube" }], 
    },
  },
   {
    id: 28,
    title: "Rooh 2.0",
    role: "2nd Assistant Director",
    year: "2024",
    description: "A song that shows you admire someone so much that you’re willing to loose yourself for them. It’s a love that’s pure, intense, and all-consuming",
    image: "/thumbnails/rooh2.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Qafilah",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/K2_L5On8N-M",
          platform: "youtube" }], 
    },
  },
     {
    id: 32,
    title: "Aabruu",
    role: "1st Director's Assistant",
    year: "2024",
    description: "The song captures the essence of a deep and enduring love, where the lover's dignity becomes a source of immense joy.",
    image: "/thumbnails/aabruu.png",
    category: "Music Video",
    details: {
      date: "December 2024",
      location: "Kashmir, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Khan Inam-Ul-Haq , Princy Khatiwada",
      director: "Faheem Abdullah",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/8d9tcK27H0I",
          platform: "youtube" }], 
    },
  },
   {
    id: 29,
    title: "RIQQAT The Decode",
    role: "2nd Assistant Director",
    year: "2024",
    description: "The artists themselves unravel the layers of RIQQAT, exploring its rich lyrics, music, and the collaborative journey that brought it to life.",
    image: "/thumbnails/decode.png",
    category: "interview",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Multiple Artists",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/TdHVE9_9iHA",
          platform: "youtube" }], 
    },
  },
   {
    id: 30,
    title: "RIQQAT The Decode EP-2",
    role: "2nd Assistant Director",
    year: "2024",
    description: "The artists themselves unravel the layers of RIQQAT, exploring its rich lyrics, music, and the collaborative journey that brought it to life.",
    image: "/thumbnails/decode2.png",
    category: "interview",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Multiple Artists",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/ngeMq67_3sM",
          platform: "youtube" }], 
    },
  },
   {
    id: 31,
    title: "RIQQAT The Decode EP-3",
    role: "2nd Assistant Director",
    year: "2024",
    description: "The artists themselves unravel the layers of RIQQAT, exploring its rich lyrics, music, and the collaborative journey that brought it to life.",
    image: "/thumbnails/decode3.png",
    category: "interview",
    details: {
      date: "December 2024",
      location: "Mumbai, India",
      company: "Artiste First",
      artist: "Multiple Artists",
      director: "Deepak Rawat",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/TdHVE9_9iHA",
          platform: "youtube" }], 
    },
  },
{
    id: 33,
    title: "Making of Aabruu",
    role: "1st Director's Assistant",
    year: "2024",
    description: "Aabruu is a heartfelt song that expresses having pride on your lover. It delves into the emotions of love, admiration, and pride.",
    image: "/thumbnails/making1.png",
    category: "Behind the scenes",
    details: {
      date: "December 2024",
      location: "Kashmir, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Khan Inam-Ul-Haq , Princy Khatiwada",
      director: "Faheem Abdullah",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/N2_sGRTLaIs",
          platform: "youtube" }], 
    },
  },
{
    id: 34,
    title: "Making of Dhamaal",
    role: "1st Director's Assistant",
    year: "2024",
    description: "Presenting the journey and the making of the music film of Dhamaal from Arslan Nizami's latest album RIQQAT.",
    image: "/thumbnails/making2.png",
    category: "Behind the scenes",
    details: {
      date: "December 2024",
      location: "Kashmir, India",
      company: "Artiste First",
      artist: "Arslan Nizami , Quaisar Nizami ",
      director: "Faheem Abdullah",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/prEhLOAk3GI",
          platform: "youtube" }], 
    },
  },
{
    id: 35,
    title: "Making of Rooh",
    role: "2nd Assistant Director",
    year: "2024",
    description: "Presenting the journey and the making of the music film of Rooh from Arslan Nizami's latest album RIQQAT.",
    image: "/thumbnails/making3.png",
    category: "Behind the scenes",
    details: {
      date: "December 2024",
      location: "Kashmir, India",
      company: "Artiste First",
      artist: "Rekha Bhardwaj, Arslan Nizami, Shiwani Bhardwaj",
      director: "Faheem Abdullah",
      type: "Music Video",
      videos: [{ url: "https://www.youtube.com/embed/RRUdEIQ9vH8",
          platform: "youtube" }], 
    },
  },
];